name: CI/CD Pipeline (Build & Deploy)

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      frontend_tag: ${{ steps.set-tags.outputs.frontend }}
      backend_tag: ${{ steps.set-tags.outputs.backend }}

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Tags
        id: set-tags
        run: |
          FRONTEND_TAG=v.${{ github.run_number }}
          BACKEND_TAG=v.${{ github.run_number }}
          echo "frontend=$FRONTEND_TAG" >> $GITHUB_OUTPUT
          echo "backend=$BACKEND_TAG" >> $GITHUB_OUTPUT

      - name: Build & Push Frontends
        working-directory: frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/yt-frontend:${{ steps.set-tags.outputs.frontend }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/yt-frontend:${{ steps.set-tags.outputs.frontend }}

      - name: Build & Push Backend
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/yt-backend:${{ steps.set-tags.outputs.backend }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/yt-backend:${{ steps.set-tags.outputs.backend }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: FRONTEND_TAG,BACKEND_TAG
          script: |
            export FRONTEND_TAG=${{ needs.build.outputs.frontend_tag }}
            export BACKEND_TAG=${{ needs.build.outputs.backend_tag }}

            cd /home/ubuntu/k8s
            sed -i "s|image: \"umes122/yt-frontend:.*\"|image: \"umes122/yt-frontend:${FRONTEND_TAG}\"|g" frontend-deployment.yml

            sed -i "s|image: \"umes122/yt-backend:.*\"|image: \"umes122/yt-backend:${BACKEND_TAG}\"|g" backend-deployment.yml


            kubectl apply -f frontend-deployment.yml
            kubectl apply -f backend-deployment.yml
